name: "awesome-lint"
description: "Lint your READMEs with sindresorhus' awesome-lint"
author: "James Hegedus <james@jthegedus.com>"
branding:
  icon: "eye"
  color: "green"

inputs:
  awesome-lint-version:
    description: "awesome-lint package version you wish to use"
    required: false
    default: "latest"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    AWESOME_LINT_VERSION: ${{ inputs.version }}
