name: "awesome-lint versionless"
description: "Lint your READMEs with sindresorhus' awesome-lint providing the specific package version"
author: "James Hegedus <jthegedus@hey.com>"
branding:
  icon: "eye"
  color: "green"

inputs:
  awesome-lint-version:
    description: "awesome-lint package version you wish to use"
    required: false
    default: "latest"
runs:
  using: "docker"
  image: "dockerfile"
  env:
    AWESOME_LINT_VERSION: ${{ inputs.awesome-lint-version }}
